from __future__ import annotations

from typing import Any


GROUP_PREFIXES: dict[str, tuple[str, ...]] = {
    "record": ("record.",),
    "sht": ("record.", "sht.", "sensor.", "delivery."),
    "npk": ("record.", "npk.", "sensor.", "delivery."),
    "record_time": ("record.",),
    "delivery_network": ("record.", "delivery.", "network."),
    "device_system": ("record.", "device.", "sensor."),
}

CATALOG_FIELDNAMES: tuple[str, ...] = (
    "canonical_name",
    "source_path",
    "group",
    "data_type",
    "field_status",
    "description",
    "used_for_audit",
    "eligible_for_model",
    "exclusion_reason",
)

ACTIVE_FIELDS: tuple[dict[str, Any], ...] = (
    {
        "canonical_name": "record.node_id",
        "source_path": "source_record.node_id|system_record.identity.node_id",
        "group": "RECORD",
        "data_type": "string",
        "field_status": "ACTIVE",
        "description": "Logical node identifier for the telemetry event.",
        "used_for_audit": True,
        "eligible_for_model": False,
        "exclusion_reason": "",
    },
    {
        "canonical_name": "record.date_key",
        "source_path": "source_record.date_key",
        "group": "RECORD",
        "data_type": "string",
        "field_status": "ACTIVE",
        "description": "Date partition key from Firebase telemetry path.",
        "used_for_audit": True,
        "eligible_for_model": False,
        "exclusion_reason": "",
    },
    {
        "canonical_name": "record.event_key",
        "source_path": "source_record.event_key",
        "group": "RECORD",
        "data_type": "string",
        "field_status": "ACTIVE",
        "description": "Event key under the telemetry date partition.",
        "used_for_audit": True,
        "eligible_for_model": False,
        "exclusion_reason": "",
    },
    {
        "canonical_name": "record.id",
        "source_path": "derived:node_id:date_key:event_key",
        "group": "RECORD",
        "data_type": "string",
        "field_status": "DERIVED",
        "description": "Stable unique identifier for a canonical telemetry row.",
        "used_for_audit": True,
        "eligible_for_model": False,
        "exclusion_reason": "",
    },
    {
        "canonical_name": "record.source_path",
        "source_path": "source_record.source_path",
        "group": "RECORD",
        "data_type": "string",
        "field_status": "ACTIVE",
        "description": "Original Layer0 source path for the telemetry event.",
        "used_for_audit": True,
        "eligible_for_model": False,
        "exclusion_reason": "",
    },
    {
        "canonical_name": "record.source_kind",
        "source_path": "source_record.source_kind",
        "group": "RECORD",
        "data_type": "string",
        "field_status": "ACTIVE",
        "description": "Origin marker describing whether the row came from history or latest.",
        "used_for_audit": True,
        "eligible_for_model": False,
        "exclusion_reason": "",
    },
    {
        "canonical_name": "record.ts_sample",
        "source_path": "ts_sample",
        "group": "RECORD",
        "data_type": "int",
        "field_status": "ACTIVE",
        "description": "Primary sample timestamp from the telemetry payload.",
        "used_for_audit": True,
        "eligible_for_model": True,
        "exclusion_reason": "",
    },
    {
        "canonical_name": "record.ts_server",
        "source_path": "ts_server",
        "group": "RECORD",
        "data_type": "int",
        "field_status": "ACTIVE",
        "description": "Server-side timestamp associated with the telemetry event.",
        "used_for_audit": True,
        "eligible_for_model": False,
        "exclusion_reason": "",
    },
    {
        "canonical_name": "record.ts_device",
        "source_path": "ts_device",
        "group": "RECORD",
        "data_type": "int",
        "field_status": "ACTIVE",
        "description": "Device uptime or device timestamp recorded with the event.",
        "used_for_audit": True,
        "eligible_for_model": False,
        "exclusion_reason": "",
    },
    {
        "canonical_name": "record.sample_time_reconstructed",
        "source_path": "sample_time_reconstructed|packet.system_data.sample_time_reconstructed",
        "group": "RECORD",
        "data_type": "boolean",
        "field_status": "ACTIVE",
        "description": "Whether firmware reconstructed the sample time instead of reading it directly.",
        "used_for_audit": True,
        "eligible_for_model": False,
        "exclusion_reason": "",
    },
    {
        "canonical_name": "record.sample_time_local",
        "source_path": "sample_time_local|derived:local_sample_time",
        "group": "RECORD",
        "data_type": "string",
        "field_status": "ACTIVE",
        "description": "Local ISO timestamp associated with the sample time.",
        "used_for_audit": True,
        "eligible_for_model": False,
        "exclusion_reason": "",
    },
    {
        "canonical_name": "record.upload_time_local",
        "source_path": "upload_time_local|derived:local_upload_time",
        "group": "RECORD",
        "data_type": "string",
        "field_status": "ACTIVE",
        "description": "Local ISO timestamp associated with the upload/server time.",
        "used_for_audit": True,
        "eligible_for_model": False,
        "exclusion_reason": "",
    },
    {
        "canonical_name": "record.timestamp_mismatch_sec",
        "source_path": "derived:packet.system_data.sample_epoch_sec-ts_sample",
        "group": "RECORD",
        "data_type": "int",
        "field_status": "DERIVED",
        "description": "Difference between packet system sample epoch and top-level ts_sample.",
        "used_for_audit": True,
        "eligible_for_model": False,
        "exclusion_reason": "",
    },
    {
        "canonical_name": "record.delta_prev_sec",
        "source_path": "derived:ts_sample-prev_ts_sample",
        "group": "TEMPORAL",
        "data_type": "int",
        "field_status": "DERIVED",
        "description": "Elapsed sample time from the previous canonical event on the same node.",
        "used_for_audit": True,
        "eligible_for_model": True,
        "exclusion_reason": "",
    },
    {
        "canonical_name": "record.upload_delay_sec",
        "source_path": "derived:ts_server-ts_sample",
        "group": "TEMPORAL",
        "data_type": "int",
        "field_status": "DERIVED",
        "description": "Delay from sample time to server time.",
        "used_for_audit": True,
        "eligible_for_model": True,
        "exclusion_reason": "",
    },
    {
        "canonical_name": "record.gap_flag",
        "source_path": "derived:delta_prev_sec>gap_threshold_sec",
        "group": "TEMPORAL",
        "data_type": "boolean",
        "field_status": "DERIVED",
        "description": "Flag indicating a large continuity gap against the configured threshold.",
        "used_for_audit": True,
        "eligible_for_model": True,
        "exclusion_reason": "",
    },
    {
        "canonical_name": "record.missing_slot_count",
        "source_path": "derived:delta_prev_sec/expected_interval_sec",
        "group": "TEMPORAL",
        "data_type": "int",
        "field_status": "DERIVED",
        "description": "Approximate number of expected telemetry slots missing before this event.",
        "used_for_audit": True,
        "eligible_for_model": True,
        "exclusion_reason": "",
    },
    {
        "canonical_name": "record.hour_sin",
        "source_path": "derived:local_hour_phase",
        "group": "TEMPORAL",
        "data_type": "float",
        "field_status": "DERIVED",
        "description": "Sine encoding of local hour-of-day.",
        "used_for_audit": False,
        "eligible_for_model": True,
        "exclusion_reason": "",
    },
    {
        "canonical_name": "record.hour_cos",
        "source_path": "derived:local_hour_phase",
        "group": "TEMPORAL",
        "data_type": "float",
        "field_status": "DERIVED",
        "description": "Cosine encoding of local hour-of-day.",
        "used_for_audit": False,
        "eligible_for_model": True,
        "exclusion_reason": "",
    },
    {
        "canonical_name": "record.is_demo",
        "source_path": "demo_template_name|system_record.synthetic",
        "group": "RECORD",
        "data_type": "boolean",
        "field_status": "ACTIVE",
        "description": "Marks demo or synthetic telemetry that should be excluded from canonical history.",
        "used_for_audit": True,
        "eligible_for_model": False,
        "exclusion_reason": "",
    },
    {
        "canonical_name": "record.excluded_reason",
        "source_path": "derived:demo_or_synthetic_record",
        "group": "RECORD",
        "data_type": "string",
        "field_status": "DERIVED",
        "description": "Reason why the raw event was excluded from canonical history.",
        "used_for_audit": True,
        "eligible_for_model": False,
        "exclusion_reason": "",
    },
    {
        "canonical_name": "sht.temp_c",
        "source_path": "packet.sht30_data.sht_temp_c",
        "group": "SHT",
        "data_type": "float",
        "field_status": "ACTIVE",
        "description": "Air temperature measured by the SHT30 packet.",
        "used_for_audit": True,
        "eligible_for_model": True,
        "exclusion_reason": "",
    },
    {
        "canonical_name": "sht.humidity_pct",
        "source_path": "packet.sht30_data.sht_hum_pct",
        "group": "SHT",
        "data_type": "float",
        "field_status": "ACTIVE",
        "description": "Air humidity measured by the SHT30 packet.",
        "used_for_audit": True,
        "eligible_for_model": True,
        "exclusion_reason": "",
    },
    {
        "canonical_name": "sht.packet_present",
        "source_path": "derived:packet.sht30_data_exists",
        "group": "SHT",
        "data_type": "boolean",
        "field_status": "ACTIVE",
        "description": "Whether the telemetry event carried an SHT30 packet.",
        "used_for_audit": True,
        "eligible_for_model": False,
        "exclusion_reason": "",
    },
    {
        "canonical_name": "sht.retry_count",
        "source_path": "packet.sht30_data.sht_retry_count",
        "group": "SHT",
        "data_type": "int",
        "field_status": "ACTIVE",
        "description": "SHT30 retry count reported by firmware.",
        "used_for_audit": True,
        "eligible_for_model": False,
        "exclusion_reason": "",
    },
    {
        "canonical_name": "sht.read_elapsed_ms",
        "source_path": "packet.sht30_data.sht_read_elapsed_ms",
        "group": "SHT",
        "data_type": "int",
        "field_status": "ACTIVE",
        "description": "SHT30 read latency reported by firmware.",
        "used_for_audit": True,
        "eligible_for_model": False,
        "exclusion_reason": "",
    },
    {
        "canonical_name": "sht.read_ok",
        "source_path": "sensors.sht30.read_ok",
        "group": "SHT",
        "data_type": "boolean",
        "field_status": "ACTIVE",
        "description": "Primary SHT30 read_ok status from the sensor status section.",
        "used_for_audit": True,
        "eligible_for_model": False,
        "exclusion_reason": "",
    },
    {
        "canonical_name": "sht.sample_valid",
        "source_path": "sensors.sht30.sample_valid",
        "group": "SHT",
        "data_type": "boolean",
        "field_status": "ACTIVE",
        "description": "Primary SHT30 sample_valid status from the sensor status section.",
        "used_for_audit": True,
        "eligible_for_model": False,
        "exclusion_reason": "",
    },
    {
        "canonical_name": "sht.status",
        "source_path": "sensors.sht30.status",
        "group": "SHT",
        "data_type": "string",
        "field_status": "ACTIVE",
        "description": "Normalized SHT30 status string.",
        "used_for_audit": True,
        "eligible_for_model": False,
        "exclusion_reason": "",
    },
    {
        "canonical_name": "sht.error_code",
        "source_path": "sensors.sht30.error_code",
        "group": "SHT",
        "data_type": "string",
        "field_status": "ACTIVE",
        "description": "Normalized SHT30 error code.",
        "used_for_audit": True,
        "eligible_for_model": False,
        "exclusion_reason": "",
    },
    {
        "canonical_name": "sht.valid",
        "source_path": "derived:sht_status_and_packet",
        "group": "SHT",
        "data_type": "boolean",
        "field_status": "DERIVED",
        "description": "True only when the SHT30 packet is present and the sensor status is clean.",
        "used_for_audit": True,
        "eligible_for_model": True,
        "exclusion_reason": "",
    },
    {
        "canonical_name": "sht.fault",
        "source_path": "derived:sht_status_and_error_code",
        "group": "SHT",
        "data_type": "boolean",
        "field_status": "DERIVED",
        "description": "Tri-state SHT30 fault flag built from sensor status and error evidence.",
        "used_for_audit": True,
        "eligible_for_model": False,
        "exclusion_reason": "",
    },
    {
        "canonical_name": "sht.missing_packet",
        "source_path": "derived:not_sht_packet_present",
        "group": "SHT",
        "data_type": "boolean",
        "field_status": "DERIVED",
        "description": "True when the SHT30 packet is absent for this event.",
        "used_for_audit": True,
        "eligible_for_model": False,
        "exclusion_reason": "",
    },
    {
        "canonical_name": "npk.soil_temp_c",
        "source_path": "packet.npk_data.temp",
        "group": "NPK",
        "data_type": "float",
        "field_status": "ACTIVE",
        "description": "Soil temperature measured in the NPK packet.",
        "used_for_audit": True,
        "eligible_for_model": True,
        "exclusion_reason": "",
    },
    {
        "canonical_name": "npk.soil_moisture_pct",
        "source_path": "packet.npk_data.hum",
        "group": "NPK",
        "data_type": "float",
        "field_status": "ACTIVE",
        "description": "Soil moisture measured in the NPK packet.",
        "used_for_audit": True,
        "eligible_for_model": True,
        "exclusion_reason": "",
    },
    {
        "canonical_name": "npk.ph",
        "source_path": "packet.npk_data.ph",
        "group": "NPK",
        "data_type": "float",
        "field_status": "ACTIVE",
        "description": "Soil pH measured in the NPK packet.",
        "used_for_audit": True,
        "eligible_for_model": True,
        "exclusion_reason": "",
    },
    {
        "canonical_name": "npk.ec",
        "source_path": "packet.npk_data.ec",
        "group": "NPK",
        "data_type": "float",
        "field_status": "ACTIVE",
        "description": "Soil EC measured in the NPK packet.",
        "used_for_audit": True,
        "eligible_for_model": True,
        "exclusion_reason": "",
    },
    {
        "canonical_name": "npk.n_proxy",
        "source_path": "packet.npk_data.N",
        "group": "NPK",
        "data_type": "float",
        "field_status": "ACTIVE",
        "description": "Proxy nitrogen reading from the NPK packet.",
        "used_for_audit": True,
        "eligible_for_model": True,
        "exclusion_reason": "",
    },
    {
        "canonical_name": "npk.p_proxy",
        "source_path": "packet.npk_data.P",
        "group": "NPK",
        "data_type": "float",
        "field_status": "ACTIVE",
        "description": "Proxy phosphorus reading from the NPK packet.",
        "used_for_audit": True,
        "eligible_for_model": True,
        "exclusion_reason": "",
    },
    {
        "canonical_name": "npk.k_proxy",
        "source_path": "packet.npk_data.K",
        "group": "NPK",
        "data_type": "float",
        "field_status": "ACTIVE",
        "description": "Proxy potassium reading from the NPK packet.",
        "used_for_audit": True,
        "eligible_for_model": True,
        "exclusion_reason": "",
    },
    {
        "canonical_name": "npk.packet_present",
        "source_path": "derived:packet.npk_data_exists",
        "group": "NPK",
        "data_type": "boolean",
        "field_status": "ACTIVE",
        "description": "Whether the telemetry event carried an NPK packet.",
        "used_for_audit": True,
        "eligible_for_model": False,
        "exclusion_reason": "",
    },
    {
        "canonical_name": "npk.error_code_raw",
        "source_path": "packet.npk_data.error_code_raw",
        "group": "NPK",
        "data_type": "int",
        "field_status": "ACTIVE",
        "description": "Raw numeric error code emitted by the NPK packet layer.",
        "used_for_audit": True,
        "eligible_for_model": False,
        "exclusion_reason": "",
    },
    {
        "canonical_name": "npk.crc_ok",
        "source_path": "packet.npk_data.crc_ok",
        "group": "NPK",
        "data_type": "boolean",
        "field_status": "ACTIVE",
        "description": "CRC status from the NPK packet.",
        "used_for_audit": True,
        "eligible_for_model": False,
        "exclusion_reason": "",
    },
    {
        "canonical_name": "npk.frame_ok",
        "source_path": "packet.npk_data.frame_ok",
        "group": "NPK",
        "data_type": "boolean",
        "field_status": "ACTIVE",
        "description": "Frame integrity status from the NPK packet.",
        "used_for_audit": True,
        "eligible_for_model": False,
        "exclusion_reason": "",
    },
    {
        "canonical_name": "npk.signal_present",
        "source_path": "packet.npk_data.npk_signal_present",
        "group": "NPK",
        "data_type": "boolean",
        "field_status": "ACTIVE",
        "description": "Whether the NPK protocol signal was detected.",
        "used_for_audit": True,
        "eligible_for_model": False,
        "exclusion_reason": "",
    },
    {
        "canonical_name": "npk.values_valid",
        "source_path": "packet.npk_data.npk_values_valid",
        "group": "NPK",
        "data_type": "boolean",
        "field_status": "ACTIVE",
        "description": "Whether the NPK packet values passed the packet-level validation.",
        "used_for_audit": True,
        "eligible_for_model": False,
        "exclusion_reason": "",
    },
    {
        "canonical_name": "npk.retry_count",
        "source_path": "packet.npk_data.retry_count",
        "group": "NPK",
        "data_type": "int",
        "field_status": "ACTIVE",
        "description": "NPK retry count reported by firmware.",
        "used_for_audit": True,
        "eligible_for_model": False,
        "exclusion_reason": "",
    },
    {
        "canonical_name": "npk.consecutive_fail_count",
        "source_path": "packet.npk_data.consecutive_fail_count",
        "group": "NPK",
        "data_type": "int",
        "field_status": "ACTIVE",
        "description": "NPK consecutive failure count reported by firmware.",
        "used_for_audit": True,
        "eligible_for_model": False,
        "exclusion_reason": "",
    },
    {
        "canonical_name": "npk.read_duration_ms",
        "source_path": "packet.npk_data.read_duration_ms",
        "group": "NPK",
        "data_type": "int",
        "field_status": "ACTIVE",
        "description": "NPK packet read duration in milliseconds.",
        "used_for_audit": True,
        "eligible_for_model": False,
        "exclusion_reason": "",
    },
    {
        "canonical_name": "npk.read_ok",
        "source_path": "sensors.npk.read_ok",
        "group": "NPK",
        "data_type": "boolean",
        "field_status": "ACTIVE",
        "description": "Primary NPK read_ok status from the sensor status section.",
        "used_for_audit": True,
        "eligible_for_model": False,
        "exclusion_reason": "",
    },
    {
        "canonical_name": "npk.sample_valid",
        "source_path": "sensors.npk.sample_valid",
        "group": "NPK",
        "data_type": "boolean",
        "field_status": "ACTIVE",
        "description": "Primary NPK sample_valid status from the sensor status section.",
        "used_for_audit": True,
        "eligible_for_model": False,
        "exclusion_reason": "",
    },
    {
        "canonical_name": "npk.status",
        "source_path": "sensors.npk.status",
        "group": "NPK",
        "data_type": "string",
        "field_status": "ACTIVE",
        "description": "Normalized NPK status string.",
        "used_for_audit": True,
        "eligible_for_model": False,
        "exclusion_reason": "",
    },
    {
        "canonical_name": "npk.error_code",
        "source_path": "sensors.npk.error_code",
        "group": "NPK",
        "data_type": "string",
        "field_status": "ACTIVE",
        "description": "Normalized NPK sensor error code.",
        "used_for_audit": True,
        "eligible_for_model": False,
        "exclusion_reason": "",
    },
    {
        "canonical_name": "npk.valid",
        "source_path": "derived:npk_status_and_packet",
        "group": "NPK",
        "data_type": "boolean",
        "field_status": "DERIVED",
        "description": "True only when the NPK packet is present and packet plus sensor status are clean.",
        "used_for_audit": True,
        "eligible_for_model": True,
        "exclusion_reason": "",
    },
    {
        "canonical_name": "npk.fault",
        "source_path": "derived:npk_status_and_error_code",
        "group": "NPK",
        "data_type": "boolean",
        "field_status": "DERIVED",
        "description": "Tri-state NPK fault flag built from sensor status and packet integrity evidence.",
        "used_for_audit": True,
        "eligible_for_model": False,
        "exclusion_reason": "",
    },
    {
        "canonical_name": "npk.protocol_fault",
        "source_path": "derived:npk_crc_frame_signal_values",
        "group": "NPK",
        "data_type": "boolean",
        "field_status": "DERIVED",
        "description": "Tri-state NPK protocol fault built from CRC, frame, signal, and values flags.",
        "used_for_audit": True,
        "eligible_for_model": False,
        "exclusion_reason": "",
    },
    {
        "canonical_name": "npk.missing_packet",
        "source_path": "derived:not_npk_packet_present",
        "group": "NPK",
        "data_type": "boolean",
        "field_status": "DERIVED",
        "description": "True when the NPK packet is absent for this event.",
        "used_for_audit": True,
        "eligible_for_model": False,
        "exclusion_reason": "",
    },
    {
        "canonical_name": "sensor.any_fault",
        "source_path": "derived:sht_fault_or_npk_fault",
        "group": "SENSOR",
        "data_type": "boolean",
        "field_status": "DERIVED",
        "description": "Aggregate fault flag across both sensor branches.",
        "used_for_audit": True,
        "eligible_for_model": False,
        "exclusion_reason": "",
    },
    {
        "canonical_name": "sensor.all_packets_missing",
        "source_path": "derived:not_sht_packet_present_and_not_npk_packet_present",
        "group": "SENSOR",
        "data_type": "boolean",
        "field_status": "DERIVED",
        "description": "True when both primary sensor packets are absent.",
        "used_for_audit": True,
        "eligible_for_model": False,
        "exclusion_reason": "",
    },
    {
        "canonical_name": "delivery.replayed_raw",
        "source_path": "replayed|system_record.sync.replayed",
        "group": "DELIVERY",
        "data_type": "boolean",
        "field_status": "ACTIVE",
        "description": "Replay flag as reported by firmware or sync metadata.",
        "used_for_audit": True,
        "eligible_for_model": False,
        "exclusion_reason": "",
    },
    {
        "canonical_name": "delivery.was_buffered_raw",
        "source_path": "was_buffered|system_record.sync.buffered",
        "group": "DELIVERY",
        "data_type": "boolean",
        "field_status": "ACTIVE",
        "description": "Buffer flag as reported by firmware or sync metadata.",
        "used_for_audit": True,
        "eligible_for_model": False,
        "exclusion_reason": "",
    },
    {
        "canonical_name": "delivery.is_buffered_replay",
        "source_path": "derived:replayed_or_buffered",
        "group": "DELIVERY",
        "data_type": "boolean",
        "field_status": "DERIVED",
        "description": "Derived flag for any event that was buffered or replayed.",
        "used_for_audit": True,
        "eligible_for_model": True,
        "exclusion_reason": "",
    },
    {
        "canonical_name": "delivery.fallback_used",
        "source_path": "fallback_used",
        "group": "DELIVERY",
        "data_type": "boolean",
        "field_status": "ACTIVE",
        "description": "Legacy fallback flag preserved when the raw payload exposes it.",
        "used_for_audit": True,
        "eligible_for_model": False,
        "exclusion_reason": "",
    },
    {
        "canonical_name": "delivery.buffer_reason",
        "source_path": "buffer_reason|system_record.sync.buffer_reason_code",
        "group": "DELIVERY",
        "data_type": "string",
        "field_status": "ACTIVE",
        "description": "Normalized delivery degradation reason.",
        "used_for_audit": True,
        "eligible_for_model": False,
        "exclusion_reason": "",
    },
    {
        "canonical_name": "delivery.buffered_at_ms",
        "source_path": "buffered_at_ms",
        "group": "DELIVERY",
        "data_type": "int",
        "field_status": "RAW_ONLY",
        "description": "Optional raw buffered timestamp when firmware provides it.",
        "used_for_audit": True,
        "eligible_for_model": False,
        "exclusion_reason": "Not present in the current firmware schema.",
    },
    {
        "canonical_name": "delivery.replayed_at_ms",
        "source_path": "replayed_at_ms",
        "group": "DELIVERY",
        "data_type": "int",
        "field_status": "RAW_ONLY",
        "description": "Optional raw replay timestamp when firmware provides it.",
        "used_for_audit": True,
        "eligible_for_model": False,
        "exclusion_reason": "Not present in the current firmware schema.",
    },
    {
        "canonical_name": "delivery.metadata_complete",
        "source_path": "derived:buffer_reason_and_timestamps",
        "group": "DELIVERY",
        "data_type": "boolean",
        "field_status": "DERIVED",
        "description": "True when replay metadata is complete enough for a detailed delivery audit.",
        "used_for_audit": True,
        "eligible_for_model": False,
        "exclusion_reason": "",
    },
    {
        "canonical_name": "network.signal_dbm",
        "source_path": "modules.sim.signal_dbm|sim_record.network.signal_dbm",
        "group": "NETWORK",
        "data_type": "int",
        "field_status": "ACTIVE",
        "description": "Primary signal strength value retained in the canonical analytical schema.",
        "used_for_audit": True,
        "eligible_for_model": True,
        "exclusion_reason": "",
    },
    {
        "canonical_name": "network.gprs",
        "source_path": "modules.sim.gprs|sim_record.network.pdp_active",
        "group": "NETWORK",
        "data_type": "boolean",
        "field_status": "ACTIVE",
        "description": "Whether packet data service was active for the event.",
        "used_for_audit": True,
        "eligible_for_model": False,
        "exclusion_reason": "",
    },
    {
        "canonical_name": "network.device_online",
        "source_path": "health.overall.online",
        "group": "NETWORK",
        "data_type": "boolean",
        "field_status": "ACTIVE",
        "description": "Overall online state retained as a lightweight device/network context signal.",
        "used_for_audit": True,
        "eligible_for_model": False,
        "exclusion_reason": "",
    },
    {
        "canonical_name": "device.wake_reason",
        "source_path": "event_meta.wake_reason|system_record.cycle.wake_reason",
        "group": "DEVICE",
        "data_type": "string",
        "field_status": "ACTIVE",
        "description": "Wake reason or reset reason label carried by the telemetry event.",
        "used_for_audit": True,
        "eligible_for_model": False,
        "exclusion_reason": "",
    },
    {
        "canonical_name": "device.cycle_duration_ms",
        "source_path": "event_meta.duration_ms|system_record.cycle.cycle_duration_ms",
        "group": "DEVICE",
        "data_type": "int",
        "field_status": "ACTIVE",
        "description": "End-to-end cycle duration in milliseconds.",
        "used_for_audit": True,
        "eligible_for_model": False,
        "exclusion_reason": "",
    },
    {
        "canonical_name": "device.heap_free",
        "source_path": "health.overall.heap_free|system_record.device_health.heap_free",
        "group": "DEVICE",
        "data_type": "int",
        "field_status": "ACTIVE",
        "description": "Heap free metric captured with the telemetry event.",
        "used_for_audit": True,
        "eligible_for_model": False,
        "exclusion_reason": "",
    },
    {
        "canonical_name": "device.reset_or_power_on",
        "source_path": "derived:wake_reason==power_on_or_reset",
        "group": "DEVICE",
        "data_type": "boolean",
        "field_status": "DERIVED",
        "description": "True when the telemetry event came from a power-on or reset wake path.",
        "used_for_audit": True,
        "eligible_for_model": False,
        "exclusion_reason": "",
    },
)

NON_ACTIVE_FIELDS: tuple[dict[str, Any], ...] = (
    {
        "canonical_name": "sht.quality",
        "source_path": "health.sht30.quality|sensors.sht30.quality",
        "group": "SHT",
        "data_type": "float",
        "field_status": "EXCLUDED",
        "description": "Legacy rule-generated quality score.",
        "used_for_audit": False,
        "eligible_for_model": False,
        "exclusion_reason": "Rule-derived and circular; not independent evidence.",
    },
    {
        "canonical_name": "npk.quality",
        "source_path": "health.npk.quality|sensors.npk.quality",
        "group": "NPK",
        "data_type": "float",
        "field_status": "EXCLUDED",
        "description": "Legacy rule-generated quality score.",
        "used_for_audit": False,
        "eligible_for_model": False,
        "exclusion_reason": "Rule-derived and circular; not independent evidence.",
    },
    {
        "canonical_name": "network.rssi",
        "source_path": "health.overall.rssi",
        "group": "NETWORK",
        "data_type": "int",
        "field_status": "EXCLUDED",
        "description": "Deprecated duplicate of the SIM signal metric.",
        "used_for_audit": False,
        "eligible_for_model": False,
        "exclusion_reason": "Superseded by modules.sim.signal_dbm.",
    },
    {
        "canonical_name": "network.registered",
        "source_path": "modules.sim.registered",
        "group": "NETWORK",
        "data_type": "boolean",
        "field_status": "RAW_ONLY",
        "description": "SIM registration state retained only for raw provenance.",
        "used_for_audit": False,
        "eligible_for_model": False,
        "exclusion_reason": "Not part of the active analytical schema.",
    },
    {
        "canonical_name": "network.attached",
        "source_path": "modules.sim.attached",
        "group": "NETWORK",
        "data_type": "boolean",
        "field_status": "RAW_ONLY",
        "description": "SIM attach state retained only for raw provenance.",
        "used_for_audit": False,
        "eligible_for_model": False,
        "exclusion_reason": "Not part of the active analytical schema.",
    },
    {
        "canonical_name": "network.transport",
        "source_path": "modules.sim.transport|packet.system_data.transport",
        "group": "NETWORK",
        "data_type": "string",
        "field_status": "RAW_ONLY",
        "description": "Transport label retained only for raw provenance.",
        "used_for_audit": False,
        "eligible_for_model": False,
        "exclusion_reason": "Configuration-like and low-variance in current exports.",
    },
    {
        "canonical_name": "device.battery_v",
        "source_path": "health.overall.battery_v",
        "group": "DEVICE",
        "data_type": "float",
        "field_status": "RAW_ONLY",
        "description": "Battery voltage placeholder retained only for raw provenance.",
        "used_for_audit": False,
        "eligible_for_model": False,
        "exclusion_reason": "Mostly placeholder in current exports.",
    },
    {
        "canonical_name": "record.schema_version",
        "source_path": "schema_version",
        "group": "RECORD",
        "data_type": "int",
        "field_status": "RAW_ONLY",
        "description": "Raw payload schema version retained only for provenance.",
        "used_for_audit": False,
        "eligible_for_model": False,
        "exclusion_reason": "Not part of the active analytical schema.",
    },
)


def catalog_entries() -> list[dict[str, Any]]:
    return [*ACTIVE_FIELDS, *NON_ACTIVE_FIELDS]


def known_catalog_field_names() -> set[str]:
    return {entry["canonical_name"] for entry in catalog_entries()}


def active_field_names() -> list[str]:
    return [entry["canonical_name"] for entry in ACTIVE_FIELDS]
